stg = "Simplilearn"
print(stg)
print(stg[1])
print(stg.index("l"))
print(stg.expandtabs()) # --> return the same copy of string
print(stg.count("l"))
print(stg.capitalize())  #-->Fist letter make small to capital
print(stg.casefold())
print(stg.encode())
print(stg.find('s'))
print(stg.format())
print(stg.split())
print(stg.__len__())
print(stg.isnumeric())
print(stg.islower())
print(stg.isprintable())
# print(stg.__reduce_ex__(12))
print(stg.__add__("a"))
print(stg.replace("S","s"))
print(stg.__reduce__("a"))